davidyoon891122/TodayWod

- TodayWod.xcodeproj/project.pbxproj
- TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- TodayWod/ContentView.swift
- TodayWod/Features/AppFeature.swift
- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Settings/SettingsFeature.swift
- TodayWod/Features/SplashFeature.swift
- TodayWod/Features/TodayWod.swift
- TodayWod/TodayWodApp.swift
- 탭뷰 화면 개발
- SwitchStore로 스플래쉬 -> 탭뷰 화면 이동 처리
- [TOW-7](https://davidyoon1122.atlassian.net/jira/software/projects/TOW/boards/1/backlog?selectedIssue=TOW-7&atlOrigin=eyJpIjoiZjNjNDE5ZGE3ODIwNDlkODgxNDg0MzA1ODQ3NjFkNmMiLCJwIjoiaiJ9)
> [TOW-7] 탭뷰 화면 개발

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/SplashFeature.swift
- TodayWod/Resources/Images.xcassets/Contents.json
ps. `Images.assets` 파일이 없어서 빌드 에러 발생으로 추가했음
> [Review] Splash

- .gitignore
- TodayWod/Features/Home/HomeFeature.swift
- 홈 디폴트 설정 화면 개발
- [TOW-19](https://davidyoon1122.atlassian.net/browse/TOW-19?atlOrigin=eyJpIjoiN2QxMmM4ZGIwMmZmNGY4NmIwYTc3NzgwMTg4MzEzNWQiLCJwIjoiaiJ9)
> [TOW-19] 홈 디폴트 설정 화면 개발

- TodayWod.xcodeproj/project.pbxproj
- TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- TodayWod/Features/Onboarding/GenderSelect/GenderSelectFeature.swift
- TodayWod/Features/Root/TodayWod.swift
- TodayWod/Manager/UserDefaultsManager.swift
- TodayWod/Model/GenderType.swift
- TodayWod/Model/LevelType.swift
- TodayWod/Model/OnboardingUserInfoModel.swift
* OnboardingUserInfoModel 추가
* SwitchStore 연결 부 변경
* UserDefaultsManager 함수 추가
* [TOW-18](https://davidyoon1122.atlassian.net/browse/TOW-18?atlOrigin=eyJpIjoiYjQ2N2E2YzM0OWUzNGMxNTk5MjgyMjVkMzc4OTMwZTQiLCJwIjoiaiJ9)
> [TOW-18] 온보딩 모델 추가 

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
- 키 입력 화면 개발
- [TOW-31](https://davidyoon1122.atlassian.net/browse/TOW-31?atlOrigin=eyJpIjoiYjZiY2Q1YzJkNmI5NGMyNWJkNDIxNDNmZDM1M2QxMmMiLCJwIjoiaiJ9)
- @jiyeonO 추석 연휴로 리뷰 필요 커멘트만 남기고 머지 합니다.
- 리뷰 필요
> [TOW-31] 키 입력 화면 개발

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
- 몸무게 입력 화면 개발
- [TOW-33](https://davidyoon1122.atlassian.net/browse/TOW-33?atlOrigin=eyJpIjoiYzk5OTFjZGIyYWQ3NDc0YmJhNGY2YjgxZjkzZGE2NWEiLCJwIjoiaiJ9)
> [TOW-33] 몸무게 입력 화면 개발

- TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Model/MethodType.swift
- TodayWod/Model/OnboardingUserInfoModel.swift
* 레벨 선택 -> 운동 방법 선택 시 온보딩 데이터 저장하도록 수정
* 온보딩 데이터 확장(운동 방법 포함)
* [TOW-35](https://davidyoon1122.atlassian.net/browse/TOW-35?atlOrigin=eyJpIjoiZGQyN2VkZmY0Mjk2NGU2ZjllNzQwMmNkMjM1YTgxMDQiLCJwIjoiaiJ9)
> [TOW-35] 저장 로직 위치 변경

- TodayWod/ContentView.swift
- TodayWod/Features/Onboarding/Gender/GenderSelectFeature.swift
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
- TodayWod/Features/Root/TodayWod.swift
- TodayWod/Features/Tab/AppFeature.swift
- 네비게이션 전체 컨트롤을 위한 구조 변경
- 온보딩 -> 홈, 홈 -> 온보딩 이동 처리 추가
- [TOW-28](https://davidyoon1122.atlassian.net/browse/TOW-28?atlOrigin=eyJpIjoiMWM2ZDc3NTE4NzkxNGNlMzkwMTM1NzE5NTAyNmNkYWQiLCJwIjoiaiJ9)
> [TOW-28] 온보딩 -> 홈 이동 처리 및 네비게이션 구조 변경

- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
* 텍스트필드 포커스 처리
* [TOW-36](https://davidyoon1122.atlassian.net/browse/TOW-36?atlOrigin=eyJpIjoiZDc4YzI1MTJlMGZmNDdmMzk1YWMyNDYxMzExODJmOTYiLCJwIjoiaiJ9)
> [TOW-36] 텍스트필드 포커스 처리

- TodayWod/Features/Common/CustomView/CustomTabView.swift
- TodayWod/Features/Tab/AppFeature.swift
> [TOW-57] 커스텀 탭바 패딩 위치 변경

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Home/WorkoutConfirmationFeature.swift
- TodayWod/Features/Settings/MyActivityFeature.swift
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* 운동 완료 확인 화면 개발
* [TOW-56](https://davidyoon1122.atlassian.net/browse/TOW-56?atlOrigin=eyJpIjoiNjQ3MWVhOGI4ZWEzNDAxODlhMjg5MTIwNjc0OTYxOTEiLCJwIjoiaiJ9
> [TOW-56] 운동 완료 확인 화면 개발

- TodayWod.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- TodayWod/Extensions/Extension+String.swift
- TodayWod/Features/Onboarding/Method/Description/MethodDescriptionFeature.swift
* SwiftUI 모디파이어가 없기 때문에, String extension 변수로 char 기준 줄바꿈 처리
* [TOW-76](https://davidyoon1122.atlassian.net/browse/TOW-76?atlOrigin=eyJpIjoiNTdmZDk0MzAyM2JiNDU3M2I2YzYxOWI4YjI3MzlhZDUiLCJwIjoiaiJ9)
> [TOW-76] lineBreakMode char 기준 함수 개발

- TodayWod/Features/Home/WorkOut/Detail/Row/WodView.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- [TOW-78](https://davidyoon1122.atlassian.net/browse/TOW-78?atlOrigin=eyJpIjoiM2E0OWExY2M3YjkyNDk4NmFhOTc1ODA0YzI5N2RkZDAiLCJwIjoiaiJ9)
> [TOW-78][iOS][details] Cool down  영역 > 분 수정시 화면이 이동되어 수정 불가한 현상

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Common/Modifier/BottomSheetModifier.swift
- TodayWod/Features/MyActivity/MyPage/ModifyProfile/ModifyProfileFeature.swift
- TodayWod/Features/MyActivity/MyPage/ModifyWeight/ModifyWeightFeature.swift
- TodayWod/Features/MyActivity/MyPage/MyInfo/MyInfoView.swift
- TodayWod/Features/MyActivity/MyPage/Profile/ProfileView.swift
- TodayWod/Features/MyActivity/MyPage/VersionInfo/VersionInfoView.swift
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Level/LevelCardView.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/Description/MethodDescriptionFeature.swift
- TodayWod/Features/Onboarding/Method/MethodMenuView.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
- TodayWod/Features/Splash/SplashFeature.swift
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* [TOW-41](https://davidyoon1122.atlassian.net/browse/TOW-41?atlOrigin=eyJpIjoiNzUxZTNhOWRlYTRiNDIzNGIyZjgwNzkyZjg3YTI2YjUiLCJwIjoiaiJ9)
* 상수처리
* 서브 뷰 분리
* 바텀쉬트 모디파이어 동적 높이 계산으로 스냅 클로즈 처리로 수정
> [TOW-41] 리팩터링 1차

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
> [BugFix] xcdatamodelId 파일 proj 경로에 추가 & Renaming

- TodayWod/Features/Home/WorkOut/Main/WorkOutListFeature.swift
- TodayWod/InternalStorage/WodClient.swift
- TodayWod/InternalStorage/WodCoreDataProvider.swift
* 쓰레드 변경 시 발생하는 이슈 처리를 위해 perform으로 동일 쓰레드에서 클로저 실행 되도록 수정
* [TOW-106](https://davidyoon1122.atlassian.net/browse/TOW-106?atlOrigin=eyJpIjoiNzQyOGExNWVjNjEzNGYzYWJhMmIyZjJlYTFlY2ZlNjkiLCJwIjoiaiJ9)
> [TOW-106] perform 적용

- TodayWod/APIClient/APIClient.swift
- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/InternalStorage/WodClient.swift
- TodayWod/InternalStorage/WodCoreDataProvider.swift
- TodayWod/Repository/ProgramRepository.swift
* Program API 요청하여 받아온 값 코어데이터에 저장
* 데이터 로드 코어 데이터에서 하도록 수정
* [TOW-107](https://davidyoon1122.atlassian.net/browse/TOW-107?atlOrigin=eyJpIjoiMWZhN2U2OGFmZjRhNGE3NTk1YjRhYTNjNWYwZDU5YWQiLCJwIjoiaiJ9)
> [TOW-107] Program 통신 후 코어 데이터 세팅 처리

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Tools/Logger.swift
* OSLog 추가
* [TOW-108](https://davidyoon1122.atlassian.net/browse/TOW-108?atlOrigin=eyJpIjoiNWIxNDJlNzUwZDAwNGIyOGFkNjFkZDNhMzcxYjFkNjMiLCJwIjoiaiJ9)
> [TOW-108] 로그 시스템 적용

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
- TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationType.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-89](https://davidyoon1122.atlassian.net/browse/TOW-89?atlOrigin=eyJpIjoiZmViY2I2YTRjMGVlNGE1MDllMjhmYjJhOTg3ODA2ZjgiLCJwIjoiaiJ9)
- 운동 종료 케이스 분기
- 운동 중단
- 모든 Wod 성공으로 운동 종료
> [TOW-89][TW][iOS] 단순 운동종료 케이스 구현

- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* 빈 화면에서 프로그램 세팅하는 기능 추가
* TODO: - hasWod 세팅 하는 방식 고민해 보아야 함
* [TOW-109](https://davidyoon1122.atlassian.net/browse/TOW-109?atlOrigin=eyJpIjoiNWFlZjMyMzBjOGZkNDg3YjlkOTY5ZjRjNGViYWNiZWEiLCJwIjoiaiJ9)
> [TOW-109] 빈 화면 프로그램 세팅 기능 추가

- TodayWod/Entity/CoreData/WodSetCoreEntity+CoreDataClass.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/InternalStorage/WodClient.swift
- TodayWod/InternalStorage/WodCoreDataProvider.swift
- [TOW-95](https://davidyoon1122.atlassian.net/browse/TOW-95?atlOrigin=eyJpIjoiNzM5ODEzNDA2YmVlNDdiYWI1NDNlNjUxMWVhODQzNTEiLCJwIjoiaiJ9)
> [TOW-95][TW][iOS] User Custom Program 데이터 저장 CoreData로 변경

- TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Manager/UserDefaultsManager.swift
* 유저 디폴트에 프로그램 세팅 여부 추가
* [TOW-114](https://davidyoon1122.atlassian.net/browse/TOW-114?atlOrigin=eyJpIjoiMjhmYWFjMzI1MGUyNGYzOGE2NDllODRkMWIyM2U3MjgiLCJwIjoiaiJ9)
> [TOW-114] isLaunchProgram 세팅

- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- [TOW-98](https://davidyoon1122.atlassian.net/browse/TOW-98?atlOrigin=eyJpIjoiNWZlMzYzZTEwNDkxNDU5ZmIwMzE5M2NkZDI1NGU4NjMiLCJwIjoiaiJ9)
> [TOW-98][iOS][details] 분,회 수정완료 후 키패드가 고정되어 노출되는 현상

- TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Tab/AppFeature.swift
* @Shared 적용으로 탭바 숨김 처리 기능 추가
* [TOW-101](https://davidyoon1122.atlassian.net/browse/TOW-101?atlOrigin=eyJpIjoiMzBmOWM2MmJjOGM4NGQwOGI2YzBiMjUyMmY2NTU2YWYiLCJwIjoiaiJ9)
> [TOW-101] 탭바 숨김 처리 기능 추가

- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Tab/AppFeature.swift
- TodayWod/Manager/UserDefaultsManager.swift
* 운동방식, 레벨 변경 시 초기화 작업 개발
* 선행 PR TOW-115
* [TOW-97](https://davidyoon1122.atlassian.net/browse/TOW-97?atlOrigin=eyJpIjoiOWU3NzgxMmRkMjU1NGIzNGIwMGYxZWJkZmQ1NzRhYmUiLCJwIjoiaiJ9)
> [TOW-97] 운동방식, 레벨 변경 시 초기화 작업 개발

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Common/CustomView/CustomTabView.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Tab/AppFeature.swift
- TodayWod/Model/Tab/TabMenuType.swift
- [TOW-117](https://davidyoon1122.atlassian.net/browse/TOW-117?atlOrigin=eyJpIjoiY2Q2OTY3MjBlOGFjNDVlM2IzNTRjZTViMDAyMDcxODAiLCJwIjoiaiJ9)
> [TOW-117][TW][iOS] Record 화면 종료 후 탭 이동 구현

- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
- TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
* 커서 왼쪽에서 시작하도록 변경
* 이슈: 3자리 -> 2자리로 변경 시 텍스트 필드 벌어지는 이슈
> [TOW-136] 커서 위치 변경

- TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Model/ProgramsModel.swift
- TodayWod/Model/WorkoutModel.swift
- [TOW-137](https://davidyoon1122.atlassian.net/browse/TOW-137?atlOrigin=eyJpIjoiOTdlMGZjZGUzYjZjNGNjNGE0ZDhjYzY4MGVhOTFkNDgiLCJwIjoiaiJ9)
- 로직적인 부분들이라 이해 돕기 위해 설명 comment로 적어놨습니다
- 기획 의도에 맞춰 수정
- 모든 운동 완료 시 성공이 아니라, 아래 케이스 포함하여 성공으로 처리하도록 수정
- 사용자 강제 운동 종료
- 세트 중 한개라도 성공 시
> [BugFix][TOW-137][iOS][Main] 운동 완료했을 경우, 한주 간 운동 목록 >  Done 표시되지 않는 현상

- TodayWod.xcodeproj/project.pbxproj
- TodayWod.xcworkspace/contents.xcworkspacedata
- TodayWod.xcworkspace/xcshareddata/swiftpm/Package.resolved
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* 모듈 분리를 위한 Workspace 적용
* [TOW-91](https://davidyoon1122.atlassian.net/browse/TOW-91?atlOrigin=eyJpIjoiZGMyMTAyODIwZjI4NGE2NmEyZjE5MWY0NDczZmMyMmEiLCJwIjoiaiJ9)
> [TOW-91] Workspace 적용

- TodayWod.xcodeproj/project.pbxproj
- TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
- TodayWod/Features/Home/WorkOut/Detail/Row/WodSetDefaultView.swift
- TodayWod/Features/Home/WorkOut/Detail/Row/WodSetView.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
* 타이머 세팅 뷰 개발
* [TOW-143](https://davidyoon1122.atlassian.net/browse/TOW-143?atlOrigin=eyJpIjoiODNhZDgxMWMzZWM4NDYzMGE4NGQ5MTY3NWU1YjQ1NDAiLCJwIjoiaiJ9)
> [TOW-143] 타이머 세팅 뷰 개발

- TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
- [TOW-152](https://davidyoon1122.atlassian.net/browse/TOW-152?atlOrigin=eyJpIjoiZjZmYWQ1MWM0OTE2NDVjOGE3YTYwNTBmZGY5ZDlhYzQiLCJwIjoiaiJ9)
[StackOverFlow-Disable default button click animation in SwiftUI](https://stackoverflow.com/questions/61593453/disable-default-button-click-animation-in-swiftui)
> [BugFix][TOW-152][iOS][details] 세트삭제,추가 버튼 tap > 버튼에 애니메이션이 적용된 현상

- TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- 홈 상세에서 뒤로가기 버튼 클릭 시 팝업 노출하도록 수정
- 단, 시작하기 버튼을 누르지 않았거나 한개의 완료도 없을 시 팝업 미노출 & 운동종료 버튼 비활성화
- [TOW-187](https://davidyoon1122.atlassian.net/browse/TOW-187?atlOrigin=eyJpIjoiZTBkMDk2MTBkZjZlNDY0MGI5OTIwNzVkOTE2ZGY3ZDciLCJwIjoiaiJ9)
> [TOW-187][TW][iOS] 운동 진행 중 상세에서 벗어날 때 종료 확인 팝업 띄우기

- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Model/WorkoutModel.swift
- 홈 상세 완료 조건 : 모든 운동 성공
- Record 완료 조건 : 세트 중 하나라도 완료했다면 완료한 운동 개수에 포함
- [TOW-189](https://davidyoon1122.atlassian.net/browse/TOW-189?atlOrigin=eyJpIjoiODJiZGQ2YjIwNmJmNDE3ZDg5NDE2YWQ2YmY3YWJmZTMiLCJwIjoiaiJ9)
> [TOW-189][TW][iOS] 운동 완료 조건 변경

- TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/Row/WorkoutDetailContentFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- 세트가 한개만 남았을 때 "세트 삭제"를 눌렀을 경우 팝업 노출하도록 수정
- [TOW-192](https://davidyoon1122.atlassian.net/browse/TOW-192?atlOrigin=eyJpIjoiZTQ4YmU5MWM2Y2JjNDFjYmI0Yzk2NWJhNTRhOGRhZTkiLCJwIjoiaiJ9)
> [BugFix][TOW-192][iOS] 세트 삭제 조건 변경

- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-183](https://davidyoon1122.atlassian.net/browse/TOW-183?atlOrigin=eyJpIjoiZGE4MmVlYWMxMmZiNGI0ZjhhNjg4YzNjN2FlNTM3MDkiLCJwIjoiaiJ9)
> [TOW-183][TW][iOS] Main > [새로운 도전하기] tap > Alert 추가

- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-188](https://davidyoon1122.atlassian.net/browse/TOW-188?atlOrigin=eyJpIjoiMjc4YjNkMDEwNWIyNDJiNGE5MGJjY2Q4YmRmMjVkMjgiLCJwIjoiaiJ9)
> [TOW-188][TW][iOS] 한번 운동 완료&종료 된 경우 Record 화면 이동 처리

- TodayWod/Features/Home/WorkOut/Completed/Row/WorkoutCompletedTopView.swift
- [TOW-176](https://davidyoon1122.atlassian.net/browse/TOW-176?atlOrigin=eyJpIjoiMTlkYWIyZWU5MDYxNDYyMmFjMzdmOTZjMTAxZjFiMTAiLCJwIjoiaiJ9)
> [TOW-176][TW][iOS] Record 화면 > 소모 Kcal -> 예상 소모 Kcal 문구 변경

- TodayWod/Features/Setting/SettingFeature.swift
- [TOW-181](https://davidyoon1122.atlassian.net/browse/TOW-181?atlOrigin=eyJpIjoiNGI1YWI3ZjViZmI5NDhhMjg1MTQ0ODZkZDJkMzRiMzciLCJwIjoiaiJ9)
> [TOW-181][TW][iOS] 내정보 > 운동 수준,운동 방식 수정 시 alert 추가

- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-185](https://davidyoon1122.atlassian.net/browse/TOW-185?atlOrigin=eyJpIjoiYjYwMTUzMjE0Nzk4NDUyNDhmNWQxMWUwZDNlNTE5NjgiLCJwIjoiaiJ9)
> [TOW-185][TW][iOS] Main > [운동 초기화] tap > Alert 추가

- TodayWod/Features/Home/WorkOut/Main/Row/WorkOutTitleView.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Model/ProgramsModel.swift
- [TOW-164](https://davidyoon1122.atlassian.net/browse/TOW-164?atlOrigin=eyJpIjoiZmU3Y2FlNDkzYTJiNDZjZDljYmQ3ZTcwMjI3NjBmYjgiLCJwIjoiaiJ9)
> [TOW-164][iOS][Main] 한주 간 운동 목록 > Done 상태가 있을 경우 [초기화]버튼 활성화되지 않는 현상

- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- [TOW-179](https://davidyoon1122.atlassian.net/browse/TOW-179?atlOrigin=eyJpIjoiY2E4ZWM0MWVlNDRiNDEwNGI4NTk0YTQxYjAwMTcxNWQiLCJwIjoiaiJ9)
> [TOW-179][iOS][Details] 운동 모두 완료 > [조금 더 할래요] > 세트 추가하지 않고 [운동 종료] 시 popup 노출되는 현상

- TodayWod/Features/Home/WorkOut/Common/WorkOutNavigationView.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-168](https://davidyoon1122.atlassian.net/browse/TOW-168?atlOrigin=eyJpIjoiZTA0ZDNhMzM3MTcyNDQ5OTk2YjcxMWFiYTE5YTJjZTAiLCJwIjoiaiJ9)
> [TOW-168][TW][iOS] 운동 중, BG로 이동 시 운동 타이머 STOP 처리

- TodayWod/Features/Home/Celebrate/CelebrateFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-199](https://davidyoon1122.atlassian.net/browse/TOW-199?atlOrigin=eyJpIjoiN2Y3NDAyYWQ2NzA0NGQyYmEyMDE2MzRiZDg4MjM3NzIiLCJwIjoiaiJ9)
> [TOW-199][iOS][Main] 한주 간 운동 모두 완료 > 승리의 순간 popup > [새로운 도전하기] 버튼 미동작하는 현상

- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
> [TOW-149] 타이머 뷰 진동 처리

- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
- TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
- TodayWod/Features/Setting/MyPage/MyPageFeature.swift
- TodayWod/Features/Setting/SettingFeature.swift
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* 마이 페이지 탭바 숨김 처리 추가
* 각 정보 수정 화면 탭바 숨김 처리 추가
* onAppear 에서 작업 Shared로 hideTabBar 변경으로 컨트롤 하도록 수정
> [TOW-190] 세팅 탭바 숨김 처리

- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-196](https://davidyoon1122.atlassian.net/browse/TOW-196?atlOrigin=eyJpIjoiNTJiMDcyMjRiMDI0NDg3YmExMTI1MmNhYWE1ODA2NWMiLCJwIjoiaiJ9)
> [TOW-196][iOS][Main] [초기화] 이후에도 [초기화]버튼이 활성화 상태로 노출되는 현상

- TodayWod/Features/Onboarding/Gender/GenderSelectFeature.swift
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
* 온보딩 백 버튼 시 데이터 저장 후 다음 화면에서 데이터 유지하도록 수정
* [TOW-163](https://davidyoon1122.atlassian.net/browse/TOW-163?atlOrigin=eyJpIjoiY2MwNDAxYWM3MTJmNDNlM2I2YWE3YjI3ZjcyZDhkYWIiLCJwIjoiaiJ9)
> [TOW-163] 온보딩 데이터 유지 처리

- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Setting/SettingFeature.swift
- [TOW-205](https://davidyoon1122.atlassian.net/browse/TOW-205?atlOrigin=eyJpIjoiZDJiZDU2NGZhMTAzNDUwOWE0MDYyNDY4YWEyMjVhODMiLCJwIjoiaiJ9)
> [TOW-205][iOS][Profile] 운동 수준,방식 수정시 노출되는 popup 시점 변경

- TodayWod/Features/Home/Celebrate/CelebrateFeature.swift
- TodayWod/Features/Home/WorkOut/Confirm/WorkoutConfirmationFeature.swift
- [TOW-200](https://davidyoon1122.atlassian.net/browse/TOW-200?atlOrigin=eyJpIjoiNjFjYzJmYzkxNDdhNGVmOGEwZTQ1Yzk1MTBjMTJhMjIiLCJwIjoiaiJ9)
> [TOW-200][iOS][details] 운동 완료 popup 영역 외 tap 시 닫히지 않도록 변경

- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- 한번 노출된 이후에는 뜨지 않도록 수정
- [TOW-217](https://davidyoon1122.atlassian.net/browse/TOW-217?atlOrigin=eyJpIjoiNDcxMDlmNzc0NmFlNDc1ZTg2MGVkMTE2NjUwOGVkZGIiLCJwIjoiaiJ9)
> [TOW-217][iOS][Main] 운동 완료 승리 팝업 > tab 이동시에도 반복적으로 노출되는 현상

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Common/SharedConstants.swift
- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Completed/WorkoutCompletedFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Setting/MyPage/MyPageFeature.swift
- TodayWod/Features/Setting/SettingFeature.swift
- TodayWod/Features/Tab/AppFeature.swift
- Human Error 발생 위험 줄이기
- [TOW-224](https://davidyoon1122.atlassian.net/browse/TOW-224?atlOrigin=eyJpIjoiOWZmMTE5MTM4ZjJkNGQ0ZTk0NWQyZTZjNTRjZDFkNjUiLCJwIjoiaiJ9)
- 이전에 얘기 나왔던 부분 반영 완료했습니다~
- [언급된 Comment](https://github.com/davidyoon891122/TodayWod/pull/99#discussion_r1831041468)
> [TOW-224][iOS][Common] Shared Key Constants 정리

- TodayWod.xcodeproj/project.pbxproj
- TodayWod.xcodeproj/xcuserdata/jiwonyoon.xcuserdatad/xcschemes/xcschememanagement.plist
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Features/Onboarding/Height/HeightInputFeature.swift
- TodayWod/Features/Onboarding/Level/LevelSelectFeature.swift
- TodayWod/Features/Onboarding/Method/MethodSelectFeature.swift
- TodayWod/Features/Onboarding/Nickname/NicknameFeature.swift
- TodayWod/Features/Onboarding/Weight/WeightInputFeature.swift
- TodayWod/Features/Root/TodayWod.swift
- TodayWod/Features/Setting/MyPage/ModifyProfile/ModifyProfileFeature.swift
- TodayWod/Features/Setting/MyPage/ModifyWeight/ModifyWeightFeature.swift
- TodayWod/Features/Setting/MyPage/MyInfo/MyInfoView.swift
- TodayWod/Features/Setting/MyPage/MyPageFeature.swift
- TodayWod/Features/Setting/SettingFeature.swift
- TodayWod/InternalStorage/UserDefaults/UserDefaultsError.swift
- TodayWod/InternalStorage/UserDefaults/UserDefaultsManager.swift
- TodayWod/StorageClient/UserDefaultsAPIClient.swift
- TodayWod/StorageClient/UserDefaultsClient.swift
* UserDefaultsManager dependency로 사용하기 위해 APIClient 생성
* 클래스 직접 호출 방식에서 UserDefaultsAPIClient 주입 방식으로 변경
> [TOW-231] UserDefaultsAPIClient 생성

- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyView.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Model/Onboading/GenderType.swift
- TodayWod/Repository/Model/OtherProgramRequestModel.swift
- TodayWod/Repository/Model/ProgramRequestModel.swift
* 프로그램 요청 시 Gender 타입에 따라 이미지 받도록 파라미터 추가
* [TOW-235](https://davidyoon1122.atlassian.net/browse/TOW-235?atlOrigin=eyJpIjoiY2IwN2VlZGIxYmExNGYwNmJkNTk5YjQzNWM5ZTkxYjAiLCJwIjoiaiJ9)
> [TOW-235] 프로그램 요청 Gender 타입 추가

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Extensions/Extension+View.swift
- TodayWod/Features/Common/Modifier/ToastModifier.swift
- TodayWod/Features/Common/Toast/ToastModel.swift
- TodayWod/Features/Common/Toast/ToastView.swift
- TodayWod/Features/Home/WorkOut/Empty/WorkOutEmptyFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Resources/Colors.xcassets/toastBG.colorset/Contents.json
- TodayWod/Resources/SwiftGen/Colors+Generated.swift
* 에러 보여줄 토스트 기능 추가
* 디자인 적용 토스트 뷰 추가
* WorkOutEmptyFeature, WorkOutFeature 화면 토스트 에러 처리 추가
* [TOW-236](https://davidyoon1122.atlassian.net/browse/TOW-236?atlOrigin=eyJpIjoiNzllN2JlMTg5NjVlNDdjY2I2NzBhOWZkNjEyZjZkZDQiLCJwIjoiaiJ9)
> [TOW-236] 토스트 기능 추가

- TodayWod/Features/Home/WorkOut/Main/Row/WorkOutDayFeature.swift
* 마지막 운동의 경우 왼쪽 디바이터 노출되지 않도록 수정
> [TOW-246] 한주간 운동 디자인 수정

- TodayWod/Features/Setting/Row/MyActivityView.swift
> [TOW-148] 운동 성별에 따른 이미지 분기 처리

- TodayWod/Features/Home/HomeFeature.swift
- TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
- TodayWod/Features/Tab/AppFeature.swift
- [TOW-247](https://davidyoon1122.atlassian.net/browse/TOW-247?atlOrigin=eyJpIjoiNjJmYjU0OTBhMjI1NGQ4Yzk4ZWUyOTNhMGZhNmFhNjUiLCJwIjoiaiJ9)
> [TOW-247][iOS] Back to Onboarding 버튼 삭제

- TodayWod/Model/DayWorkoutModel.swift
* 범위 값에서 단일 예상 칼로리 값으로 변경
* 서버 변경 미적용으로 maxExpectedCalorie 를 단일로 사용하도록 수정
* [TOW-249](https://davidyoon1122.atlassian.net/browse/TOW-249?atlOrigin=eyJpIjoiYzg1MTg4OWMyODQwNGFlZGEyNDhhZGMzYzc3Njg2MzUiLCJwIjoiaiJ9)
> [TOW-249] 예상 칼로리 표시 변경

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Common/Modifier/ColorBackgroundSheetModifier.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerSettingsFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- [TOW-253](https://davidyoon1122.atlassian.net/browse/TOW-253?atlOrigin=eyJpIjoiMTAzNjhjYTRmZmZiNGRlMTg0NzFmN2I4MWRhNmFhNzciLCJwIjoiaiJ9)
> [TOW-253][TW][iOS] 휴식 Timer & TimerSetting UI 변경 반영

- TodayWod/Features/Home/WorkOut/Common/BannerAdView.swift
- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- [TOW-259](https://davidyoon1122.atlassian.net/browse/TOW-259?atlOrigin=eyJpIjoiZWEyODg4N2MxNDdhNGY0MWIxMThlYmM4ZmQyODNmNmMiLCJwIjoiaiJ9)
> [TOW-259][TW][iOS][Detail] Background에서 Foreground 올라올 때 Timer가 무조건 시작되는 문제

- TodayWod/Features/Home/WorkOut/Detail/Timer/BreakTimerFeature.swift
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
* 액션 이름 변경
* 상태 이름 변경
* [TOW-261](https://davidyoon1122.atlassian.net/browse/TOW-261?atlOrigin=eyJpIjoiYzU5NmMzNzAyZGRjNDlmYjg2Y2FmNmU2Yjg3M2RkNGMiLCJwIjoiaiJ9)
> [TOW-261] BreakTimer 리팩터링

- TodayWod/Features/Home/WorkOut/Detail/Row/WodFeature.swift
- TodayWod/Model/WodModel.swift
* 영어 이름 이슈로 subTitle 대신 예상 칼로리 보여주기로 변경
* [TOW-264](https://davidyoon1122.atlassian.net/browse/TOW-264?atlOrigin=eyJpIjoiZjIzYjNlNjVjZjU2NDYzMDk5MmFhYjk5Y2UzN2YzOGUiLCJwIjoiaiJ9)
> [TOW-264] Wod Subtitle 변경

- TodayWod/Features/Setting/SettingFeature.swift
* sheet 스와이프 동작 시 OnAppear 호출이 안되어 탭바 숨김으로 유지되는 현상
* 기획 디자인 요건에 따라 fullScreen으로 변경 처리
* [TOW-268](https://davidyoon1122.atlassian.net/browse/TOW-268?atlOrigin=eyJpIjoiZDUwNGQ5YWI1ZmZiNDU3ZThkNDJkMDg2NjI1YTc1YzkiLCJwIjoiaiJ9)
> [TOW-268] 최근활동 선택 시 탭바 숨김 이슈 처리

- TodayWod.xcodeproj/project.pbxproj
- TodayWod/Features/Home/WorkOut/Detail/WorkOutDetailFeature.swift
- TodayWod/Features/Home/WorkOut/Main/WorkOutFeature.swift
- TodayWod/Features/Setting/SettingFeature.swift
- RealID 처리해서 올렸더니 광고가 안뜨는 현상
- Reject 사유
- 우선 AppStore 배포 후
- Admob 적용 후 재배포 실시
> [Admob] 광고 제거

- TodayWod/Features/Setting/MyPage/VersionInfo/VersionInfoFeature.swift
- TodayWod/Repository/Model/AppStoreResultRequestModel.swift
* 앱 스토어 특정 국가 대상의 앱의 country 파라미터 필요하여 값 추가 처리
* [TOW-272](https://davidyoon1122.atlassian.net/browse/TOW-272?atlOrigin=eyJpIjoiMThhNzk5M2Q1OTFmNDMwNDlkNDQ0MDlkNWU2NzIwN2IiLCJwIjoiaiJ9)
> [TOW-272] 버전 확인 파라미터 추가
